#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# This is not the current entrypoint. Use 1st-step.sh

sudo -v

if [ ! -d ~/.local/bin ] || [ ! -d ~/.icons ] || [ ! -d ~/Wallpapers ]; then
  echo "📂 Make directories"
  mkdir -p \
    ~/.local/bin \
    ~/.icons \
    ~/Wallpapers \
    ;
fi

if [ ! -d /usr/local/git ]; then
  cd /usr/local
  sudo mkdir -p git
  (
    _USER="$USER"
    _GROUP="$(id -g)"
    sudo chown "$_USER:$_GROUP" git
  )
  cd git
  sudo mkdir -p \
    lens0021 \
    femiwiki \
    gerrit \
    port \
    ;
fi

if ! cmp --silent config/.bashrc "$HOME/.bashrc"; then
  printf 'Updating bashrc...'
  mv "$HOME/.bashrc" "$HOME/.bashrc.BAK.$(date +%F)"
  cp config/.bashrc "$HOME/.bashrc"
  echo ' Done'
fi

python install_package/main.py
