#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# This is not the current entrypoint. Use 1st-step.sh

sudo -v

if [ ! -d ~/.local/bin ] || [ ! -d ~/.icons ] || [ ! -d ~/Wallpapers ]; then
  echo "📂 Make directories"
  mkdir -p \
    ~/.local/bin \
    ~/.icons \
    ~/Wallpapers \
    ;
fi

if [ ! -d /usr/local/git ]; then
  cd /usr/local
  sudo mkdir -p git
  (
    _USER="$USER"
    _GROUP="$(id -g)"
    sudo chown "$_USER:$_GROUP" git
  )
  cd git
  sudo mkdir -p \
    lens \
    femiwiki \
    gerrit \
    port \
    ;
fi

if [ ! -L "$HOME"/git ]; then
  ln -s /usr/local/git "$HOME"/git
fi

if ! cmp --silent config/.bashrc "$HOME/.bashrc"; then
  printf 'Updating bashrc...'
  if [ -e "$HOME"/.bashrc ]; then
    mv "$HOME/.bashrc" "$HOME/.bashrc.BAK.$(date +%F)"
  fi
  cp config/.bashrc "$HOME/"
  echo ' Done'
fi

if ! cmp --silent config/.tmux.conf "$HOME/.tmux.conf"; then
  printf 'Updating tmux.conf...'
  if [ -e "$HOME/.tmux.conf" ]; then
    mv "$HOME/.tmux.conf" "$HOME/.tmux.conf.BAK.$(date +%F)"
  fi
  cp config/.tmux.conf "$HOME/"
  echo ' Done'
fi

if ! cmp --silent config/rclone@.service "$HOME/.config/systemd/user/rclone@.service"; then
  printf 'Updating rclone@.service...'
  mkdir -p "$HOME/.config/systemd/user/"
  cp -f config/rclone@.service "$HOME/.config/systemd/user/"
  echo ' Done'
  systemctl --user daemon-reload
fi

if [ $(sudo dmidecode -t system | grep "Product Name" | cut -d: -f2) = " GE62 2QL" ]; then
  if [ ! -e /var/lib/gdm3/.config/monitors.xml ]; then
    mkdir -p /var/lib/gdm3/.config/
    cp -f config/monitors-msi.xml /var/lib/gdm3/.config/monitors.xml
  fi
fi

python install_package/main.py
bash installer-sh/main.sh
