#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

CWD=$(cd "$(dirname "$0")" && pwd -P)

main() {
  NAME=$1

  if "$CWD/is-installed" $NAME; then
    echo "$NAME is already installed... skip"
    return 0
  fi

  case $("$CWD"/which-distro) in
    fedora)
      install-package-dnf "$NAME"
      return 0
      ;;
  esac
  >&2 echo "Unknown $("$CWD"/which-distro)"
  return 255
}

install-package-dnf() {
  NAME=$1

  echo "🚀 install $NAME"
  sudo dnf -y install "$NAME"
}

main "$@"
