#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

CWD=$(cd "$(dirname "$0")" && pwd -P)

main() {
  NAME=$1

  case $("$CWD"/which-distro) in
    fedora)
      is-installed-rpm "$NAME"
      return 0
    ;;
  esac

  >&2 echo "Unknown $("$CWD"/which-distro)"
  return 255
}

is-installed-rpm() {
  NAME=$1

  if [ -f "$CWD"/../../cache/rpm-qa ]; then
    RPM=$(cat "$CWD"/../../cache/rpm-qa)
  else
    RPM=$(rpm -qa)
    echo "$RPM" > "$CWD"/../../cache/rpm-qa
  fi

  if echo "$RPM" | grep -q "^$NAME-"; then
    return 0
  else
    return 255
  fi
}

main "$@"
