import {
    array_contains,
} from "std/array"
import {
    dir_create,
    dir_exists,
    file_chmod,
    file_exists,
    symlink_create,
} from "std/fs"
import {
    split,
    replace,
    rpad,
} from "std/text"

fun pm_list() {
    
}

fun pm_ensure() {
    
}

main(args) {
    if args[1] == "list" {
        pm_list()?
    }

    if args[1] == "ensure" {
        if len(args) >= 2 {
            pm_ensure([args[2]])?
        } else {
            pm_ensure()?
        }
    }
}
